### ISSUE TITLE
ValueError: Unknown loss function:gdl_mse

### ISSUE THREAD

**Issue by MadMMan** [kazutotess/ML-ROM_Various_Shapes#1]
Hi,  @kazutotess How are you? I was trying to work on your repository. When I ran the "Muliti-Scale_CNN-AE.py" file I came across the **"Unknown loss function:gdl_mse**" error. In your paper, you mentioned the use of a combination of the mean squared error and the gradient difference loss as the loss function but I find no help regarding this loss function on google. If you have implemented a custom loss function then kindly do share the file so that I can get help. Following is the error while I am running the file.

Model was created.

----------------Model Configuration----------------

Model                   : Multi-scale CNN

Input shape of model    : 310, 310, 3
Shape of encoded data   :   5,   5, 4
Output shape of model   : 320, 320, 3

Optimizer               : adam
Loss function           : gdl_mse
Activation function     : relu

---------------------------------------------------

Traceback (most recent call last):
  File "Muliti-Scale_CNN-AE.py", line 232, in <module>
    main()
  File "Muliti-Scale_CNN-AE.py", line 175, in main
    layer_nm, chanel_nm, act, optimizer, loss)
  File "Muliti-Scale_CNN-AE.py", line 113, in MS_CNN_AE
    model.compile(optimizer=optimizer, loss=loss)
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\engine\training.py", line 119, in compile
    self.loss, self.output_names)
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\engine\training_utils.py", line 822, in prepare_loss_functions
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\engine\training_utils.py", line 822, in <listcomp>
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\engine\training_utils.py", line 705, in get_loss_function
    loss_fn = losses.get(loss)
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\losses.py", line 795, in get
    return deserialize(identifier)
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\losses.py", line 776, in deserialize
    printable_module_name='loss function')
  File "C:\Users\hayub.mscse18rcms\AppData\Roaming\Python\Python37\site-packages\keras\utils\generic_utils.py", line 167, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:gdl_mse

**Comment by kazutotess** [comment]
Hello, @Husnain-Ayub.
Thank you for your question and sorry for being late to reply you.
I added the function for the loss function to the script.
Therefore, the code should be work without the error.
I hope this could be your help.

**Comment by MadMMan** [comment]
Thank you for your kind reply. I hope this works for me.
